# Generated by Django 5.0.4 on 2024-05-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='datetime',
        ),
    ]
